{% set name = "ocean-model-skill-assessor" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ffa5bc0d81a43bb9aff3a78d8a36bc2b77d4066c55591af53a3517a8ddb3a45d

build:
  entry_points:
    - omsa=ocean_model_skill_assessor.CLI:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - aiohttp
    - alphashape
    - appdirs
    - cartopy
    - cf_pandas
    - cf_xarray
    - cmocean
    - datetimerange
    - extract_model
    - intake
    - intake-axds
    - intake-erddap
    - intake-xarray
    - matplotlib-base
    - numpy
    - pandas
    - pyproj
    - python >={{ python_min }}
    - pyyaml
    - requests
    - scipy
    - shapely
    - tqdm
    - xarray
    - xcmocean
    - xgcm

test:
  imports:
    - ocean_model_skill_assessor
  commands:
    - pip check
    - omsa --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/axiom-data-science/ocean-model-skill-assessor
  summary: A package to fully run the comparison between data and model to assess model skill.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
