{% set name = "ocean_model_skill_assessor" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/ocean-model-skill-assessor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 543c2fd6a2727e8bb3146be00c8ca56b57a9d32a85d1438bb727acbeb6cf3b4a

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - cartopy
    - cf_xarray
    - extract_model
    - importlib_resources
    - matplotlib-base
    - netcdf4
    - numpy
    - ocean_data_gateway
    - pandas
    - python >=3.6
    - requests
    - scipy
    - xarray

test:
  imports:
    - ocean_model_skill_assessor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/ocean-model-skill-assessor
  license: MIT
  license_file: LICENSE.txt
  summary: A package to fully run the comparison between data and model to assess model skill.
  doc_url: https://ocean-model-skill-assessor.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/ocean-model-skill-assessor

extra:
  recipe-maintainers:
    - kthyng
