{% set name = "ocean_model_skill_assessor" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/ocean-model-skill-assessor/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 66c461861d12424b3b60de8684d061dbc3e2611d6d49bdb468bde1e7edcdacd8

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - cartopy
    - cf_xarray
    - extract_model
    - importlib_resources
    - matplotlib-base
    - netcdf4
    - numpy
    - ocean_data_gateway
    - pandas
    - requests
    - scipy
    - xarray

test:
  imports:
    - ocean_model_skill_assessor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/ocean-model-skill-assessor
  license: MIT
  license_file: LICENSE.txt
  summary: 'A package to fully run the comparison between data and model to assess model skill.'
  doc_url: https://ocean-model-skill-assessor.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/ocean-model-skill-assessor

extra:
  recipe-maintainers:
    - kthyng
