{% set name = "ocean-model-skill-assessor" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ocean-model-skill-assessor-{{ version }}.tar.gz
  sha256: 0d8e1b14ee3cc95a8268211018d752fad2af7b468176f46ce0f7a16e3adff886

build:
  entry_points:
    - omsa=ocean_model_skill_assessor.CLI:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - aiohttp
    - alphashape
    - cf_pandas
    - cf_xarray
    - extract_model
    - intake
    - intake-axds
    - intake-erddap
    - intake-xarray
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.8
    - requests
    - scipy
    - tqdm
    - xarray

test:
  imports:
    - ocean_model_skill_assessor
  commands:
    - pip check
    - omsa --help
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/ocean-model-skill-assessor
  summary: A package to fully run the comparison between data and model to assess model skill.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
